import Foundation

public enum WatchOperationKind:String,Hashable,Codable,Sendable{case sessions,composerOptions,transcript,runState,pendingApprovalHead,pendingClarificationHead,tasks,taskRuns,taskRunDetail,skills,skillDetail,skillContent,memoryDocument,insightsAggregate,workspace,filePreview,gitAggregate,diagnostics,media,bots,botConversation,createSession,send,stop,respondApproval,respondClarification,controlTask,sendBot,interruptBot,runStream,botStream}
public enum WatchReadOperation:Hashable,Codable,Sendable{
 case sessions(scope:ServerScope,collection:SessionCollection,query:String?,localLimit:Int);case composerOptions(scope:ServerScope);case transcript(session:SessionKey,before:Int?,limit:Int);case runState(run:RunKey);case pendingApprovalHead(session:SessionKey);case pendingClarificationHead(session:SessionKey);case tasks(scope:ServerScope,localLimit:Int);case taskRuns(task:TaskKey,page:PageRequest);case taskRunDetail(task:TaskKey,runID:String);case skills(scope:ServerScope,query:String?,localLimit:Int);case skillDetail(skill:SkillKey);case skillContent(skill:SkillKey,fileHandle:PathHandle?);case memoryDocument(scope:ServerScope);case insightsAggregate(scope:ServerScope,days:InsightsDays);case workspace(session:SessionKey,parentPathHandle:PathHandle?);case filePreview(session:SessionKey,pathHandle:PathHandle);case gitAggregate(session:SessionKey);case diagnostics(scope:ServerScope);case media(WatchMediaDescriptor);case bots(scope:ServerScope);case botConversation(bot:BotKey)
 public var kind:WatchOperationKind{switch self{case .sessions:return.sessions;case .composerOptions:return.composerOptions;case .transcript:return.transcript;case .runState:return.runState;case .pendingApprovalHead:return.pendingApprovalHead;case .pendingClarificationHead:return.pendingClarificationHead;case .tasks:return.tasks;case .taskRuns:return.taskRuns;case .taskRunDetail:return.taskRunDetail;case .skills:return.skills;case .skillDetail:return.skillDetail;case .skillContent:return.skillContent;case .memoryDocument:return.memoryDocument;case .insightsAggregate:return.insightsAggregate;case .workspace:return.workspace;case .filePreview:return.filePreview;case .gitAggregate:return.gitAggregate;case .diagnostics:return.diagnostics;case .media:return.media;case .bots:return.bots;case .botConversation:return.botConversation}}
 public var scope:ServerScope{switch self{case .sessions(let s,_,_,_),.composerOptions(let s),.tasks(let s,_),.skills(let s,_,_),.memoryDocument(let s),.insightsAggregate(let s,_),.diagnostics(let s),.bots(let s):return s;case .transcript(let k,_,_),.pendingApprovalHead(let k),.pendingClarificationHead(let k),.workspace(let k,_),.filePreview(let k,_),.gitAggregate(let k):return k.scope;case .runState(let k):return k.session.scope;case .taskRuns(let k,_),.taskRunDetail(let k,_):return k.scope;case .skillDetail(let k),.skillContent(let k,_):return k.scope;case .media(let d):return d.scope;case .botConversation(let k):return k.scope}}
}
public enum WatchStreamOperation:Hashable,Codable,Sendable{case run(RunKey,afterEventID:String?);case bot(BotKey,replayEpoch:String?,afterSequence:Int?);public var kind:WatchOperationKind{switch self{case .run:return.runStream;case .bot:return.botStream}};public var scope:ServerScope{switch self{case .run(let k,_):return k.session.scope;case .bot(let k,_,_):return k.scope}}}
