import Foundation

extension ScopedSnapshot: Equatable where Value: Equatable {
 public static func ==(lhs:Self,rhs:Self)->Bool{lhs.schema==rhs.schema&&lhs.scope==rhs.scope&&lhs.revision==rhs.revision&&lhs.freshness==rhs.freshness&&lhs.value==rhs.value}
}
extension ScopedSnapshot: Hashable where Value: Hashable {
 public func hash(into hasher:inout Hasher){hasher.combine(schema);hasher.combine(scope);hasher.combine(revision);hasher.combine(freshness);hasher.combine(value)}
}

public enum WatchOperationResult:Hashable,Codable,Sendable{
 case sessions(ScopedSnapshot<BoundedCollection<WatchSessionSummary>>);case composerOptions(ScopedSnapshot<WatchComposerOptions>);case transcript(ScopedSnapshot<WatchTranscript>);case runState(ScopedSnapshot<WatchRunState>);case pendingApprovalHead(ScopedSnapshot<WatchAttentionHead<WatchApproval>>);case pendingClarificationHead(ScopedSnapshot<WatchAttentionHead<WatchClarification>>);case tasks(ScopedSnapshot<BoundedCollection<WatchTaskSummary>>);case taskRuns(ScopedSnapshot<BoundedPage<WatchTaskRun>>);case taskRunDetail(ScopedSnapshot<WatchTaskRunDetail>);case skills(ScopedSnapshot<BoundedCollection<WatchSkillSummary>>);case skillDetail(ScopedSnapshot<WatchSkillDetail>);case skillContent(ScopedSnapshot<WatchSkillContent>);case memoryDocument(ScopedSnapshot<WatchMemoryDocument>);case insightsAggregate(ScopedSnapshot<WatchInsightsAggregate>);case workspace(ScopedSnapshot<BoundedCollection<WatchWorkspaceEntry>>);case filePreview(ScopedSnapshot<WatchFilePreview>);case gitAggregate(ScopedSnapshot<WatchGitAggregate>);case diagnostics(ScopedSnapshot<WatchDiagnosticsProjection>);case media(WatchMediaPayload);case bots(ScopedSnapshot<[WatchBotSummary]>);case botConversation(ScopedSnapshot<WatchBotConversation>);case createdSession(CommandReceipt<SessionKey>);case startedRun(CommandReceipt<RunKey>);case mutation(CommandReceipt<EmptyValue>);case runEvent(WatchRunEvent);case botEvent(WatchBotEvent);case failure(WatchTransportFailure)
 public var kind:WatchOperationKind?{switch self{case .sessions:return.sessions;case .composerOptions:return.composerOptions;case .transcript:return.transcript;case .runState:return.runState;case .pendingApprovalHead:return.pendingApprovalHead;case .pendingClarificationHead:return.pendingClarificationHead;case .tasks:return.tasks;case .taskRuns:return.taskRuns;case .taskRunDetail:return.taskRunDetail;case .skills:return.skills;case .skillDetail:return.skillDetail;case .skillContent:return.skillContent;case .memoryDocument:return.memoryDocument;case .insightsAggregate:return.insightsAggregate;case .workspace:return.workspace;case .filePreview:return.filePreview;case .gitAggregate:return.gitAggregate;case .diagnostics:return.diagnostics;case .media:return.media;case .bots:return.bots;case .botConversation:return.botConversation;case .createdSession:return.createSession;case .startedRun:return.send;case .mutation(let r):return r.receipt.operationKind;case .runEvent:return.runStream;case .botEvent:return.botStream;case .failure:return nil}}
}
