import Foundation

enum PrivateExchangeValidationError:Error,Equatable{case unsupportedSchema,invalidDates,scopeMismatch,incompatiblePurpose,incompatiblePayload,identityMismatch,blankPayload,tooLarge}
public enum PrivateExchangeKind:String,Hashable,Codable,Sendable{case consumeDraft,resolveDirectPath}
public enum PrivateExchangePurpose:String,Hashable,Codable,Sendable{case newSessionDraft,clarificationDraft,directPathHandoff}
public enum PrivateExchangeIdentity:Hashable,Codable,Sendable{case draft(scope:ServerScope,handle:DraftHandle);case directPath(session:SessionKey,handle:PathHandle);public var scope:ServerScope{switch self{case .draft(let s,_):return s;case .directPath(let s,_):return s.scope}}}
public struct PrivateExchangeRequest:Hashable,Codable,Sendable{public let schemaVersion:UInt16;public let requestID:UUID;public let scope:ServerScope;public let kind:PrivateExchangeKind;public let purpose:PrivateExchangePurpose;public let identity:PrivateExchangeIdentity;public let createdAt:Date;public let expiresAt:Date;public init(requestID:UUID,scope:ServerScope,kind:PrivateExchangeKind,purpose:PrivateExchangePurpose,identity:PrivateExchangeIdentity,createdAt:Date,expiresAt:Date)throws{guard scope==identity.scope else{throw PrivateExchangeValidationError.scopeMismatch};guard createdAt.timeIntervalSinceReferenceDate.isFinite,expiresAt.timeIntervalSinceReferenceDate.isFinite,createdAt<expiresAt,expiresAt.timeIntervalSince(createdAt)<=300 else{throw PrivateExchangeValidationError.invalidDates};switch(kind,purpose,identity){case(.consumeDraft,.newSessionDraft,.draft),(.consumeDraft,.clarificationDraft,.draft),(.resolveDirectPath,.directPathHandoff,.directPath):break;default:throw PrivateExchangeValidationError.incompatiblePurpose};self.schemaVersion=1;self.requestID=requestID;self.scope=scope;self.kind=kind;self.purpose=purpose;self.identity=identity;self.createdAt=createdAt;self.expiresAt=expiresAt}}
public enum PrivateExchangePayload:Hashable,Codable,Sendable{case draft(handle:DraftHandle,text:String);case canonicalPath(session:SessionKey,handle:PathHandle,path:String);case failure(identity:PrivateExchangeIdentity,code:String)}
public struct PrivateExchangeResult:Hashable,Codable,Sendable{public let schemaVersion:UInt16;public let requestID:UUID;public let scope:ServerScope;public let requestKind:PrivateExchangeKind;public let requestPurpose:PrivateExchangePurpose;public let requestIdentity:PrivateExchangeIdentity;public let requestCreatedAt:Date;public let requestExpiresAt:Date;public let payload:PrivateExchangePayload;public init(request:PrivateExchangeRequest,payload:PrivateExchangePayload)throws{switch(request.kind,request.identity,payload){case(.consumeDraft,.draft(_,let expected),.draft(let actual,let text)) where expected==actual:guard !text.isEmpty,text.utf8.count<=16_384 else{throw PrivateExchangeValidationError.tooLarge};case(.resolveDirectPath,.directPath(let session,let expected),.canonicalPath(let actualSession,let actualHandle,let path)) where session==actualSession&&expected==actualHandle:guard !path.isEmpty,path.utf8.count<=16_384 else{throw PrivateExchangeValidationError.tooLarge};case(_,let identity,.failure(let actual,let code)) where identity==actual:guard !code.isEmpty,code.utf8.count<=256 else{throw PrivateExchangeValidationError.blankPayload};default:throw PrivateExchangeValidationError.identityMismatch};self.schemaVersion=1;self.requestID=request.requestID;self.scope=request.scope;self.requestKind=request.kind;self.requestPurpose=request.purpose;self.requestIdentity=request.identity;self.requestCreatedAt=request.createdAt;self.requestExpiresAt=request.expiresAt;self.payload=payload}}
