import Foundation

enum EnvelopeValidationError:Error,Equatable{case unsupportedSchema(UInt16),invalidDates,expired,scopeMismatch,kindMismatch,contextMismatch}
public enum WatchRequestEnvelope:Hashable,Codable,Sendable{
 case read(schemaVersion:UInt16,requestID:UUID,scope:ServerScope,operationKind:WatchOperationKind,operation:WatchReadOperation,createdAt:Date,expiresAt:Date)
 case stream(schemaVersion:UInt16,requestID:UUID,scope:ServerScope,operationKind:WatchOperationKind,operation:WatchStreamOperation,createdAt:Date,expiresAt:Date)
 public static func read(requestID:UUID,scope:ServerScope,operation:WatchReadOperation,createdAt:Date,expiresAt:Date)throws->Self{try validate(schema:1,scope:scope,nested:operation.scope,kind:operation.kind,expected:operation.kind,createdAt:createdAt,expiresAt:expiresAt);return .read(schemaVersion:1,requestID:requestID,scope:scope,operationKind:operation.kind,operation:operation,createdAt:createdAt,expiresAt:expiresAt)}
 public static func stream(requestID:UUID,scope:ServerScope,operation:WatchStreamOperation,createdAt:Date,expiresAt:Date)throws->Self{try validate(schema:1,scope:scope,nested:operation.scope,kind:operation.kind,expected:operation.kind,createdAt:createdAt,expiresAt:expiresAt);return .stream(schemaVersion:1,requestID:requestID,scope:scope,operationKind:operation.kind,operation:operation,createdAt:createdAt,expiresAt:expiresAt)}
 public var operationKind:WatchOperationKind{switch self{case .read(_,_,_,let k,_,_,_),.stream(_,_,_,let k,_,_,_):return k}}
 private static func validate(schema:UInt16,scope:ServerScope,nested:ServerScope,kind:WatchOperationKind,expected:WatchOperationKind,createdAt:Date,expiresAt:Date)throws{guard schema==1 else{throw EnvelopeValidationError.unsupportedSchema(schema)};guard scope==nested else{throw EnvelopeValidationError.scopeMismatch};guard kind==expected else{throw EnvelopeValidationError.kindMismatch};guard createdAt.timeIntervalSinceReferenceDate.isFinite,expiresAt.timeIntervalSinceReferenceDate.isFinite,createdAt<expiresAt else{throw EnvelopeValidationError.invalidDates}}
}
public struct WatchMutationRequest:Hashable,Codable,Sendable{public let schemaVersion:UInt16;public let requestID:UUID;public let context:CommandContext;public let operationKind:WatchOperationKind;public let operation:WatchMutationOperation;public let createdAt:Date;public let expiresAt:Date;public init(requestID:UUID,context:CommandContext,operation:WatchMutationOperation,createdAt:Date,expiresAt:Date)throws{guard context.scope==operation.scope else{throw EnvelopeValidationError.scopeMismatch};guard createdAt==context.createdAt,expiresAt==context.expiresAt else{throw EnvelopeValidationError.contextMismatch};self.schemaVersion=1;self.requestID=requestID;self.context=context;self.operationKind=operation.kind;self.operation=operation;self.createdAt=createdAt;self.expiresAt=expiresAt};private enum CodingKeys:String,CodingKey{case schemaVersion,requestID,context,operationKind,operation,createdAt,expiresAt};public init(from decoder:Decoder)throws{let c=try decoder.container(keyedBy:CodingKeys.self);let schema=try c.decode(UInt16.self,forKey:.schemaVersion);guard schema==1 else{throw EnvelopeValidationError.unsupportedSchema(schema)};let context=try c.decode(CommandContext.self,forKey:.context);let operation=try c.decode(WatchMutationOperation.self,forKey:.operation);let kind=try c.decode(WatchOperationKind.self,forKey:.operationKind);guard kind==operation.kind else{throw EnvelopeValidationError.kindMismatch};try self.init(requestID:c.decode(UUID.self,forKey:.requestID),context:context,operation:operation,createdAt:c.decode(Date.self,forKey:.createdAt),expiresAt:c.decode(Date.self,forKey:.expiresAt))}}
public struct WatchResponseEnvelope:Hashable,Codable,Sendable{public let schemaVersion:UInt16;public let requestID:UUID;public let scope:ServerScope;public let requestOperationKind:WatchOperationKind;public let requestCreatedAt:Date;public let requestExpiresAt:Date;public let commandContext:CommandContext?;public let result:WatchOperationResult;public init(requestID:UUID,scope:ServerScope,requestOperationKind:WatchOperationKind,requestCreatedAt:Date,requestExpiresAt:Date,commandContext:CommandContext?,result:WatchOperationResult)throws{guard requestCreatedAt<requestExpiresAt else{throw EnvelopeValidationError.invalidDates};if let commandContext{guard commandContext.scope==scope,commandContext.createdAt==requestCreatedAt,commandContext.expiresAt==requestExpiresAt else{throw EnvelopeValidationError.contextMismatch}};self.schemaVersion=1;self.requestID=requestID;self.scope=scope;self.requestOperationKind=requestOperationKind;self.requestCreatedAt=requestCreatedAt;self.requestExpiresAt=requestExpiresAt;self.commandContext=commandContext;self.result=result}}
