import Foundation
import Testing
@testable import WatchShared
@Suite struct CredentialContractTests{
 private func scope()throws->ServerScope{ServerScope(epoch:InstallationEpoch(rawValue:UUID()),server:ServerID(rawValue:UUID()),generation:try Generation(1))}
 @Test func canonicalPhoneWatchRoundTripsAndValidatesHTTPS()throws{let s=try scope();let n=Date();let cookie=try HTTPCookiePropertyRecord(name:"hermes_session",value:"secret",domain:"example.com",path:"/",secure:true,expiresAt:n.addingTimeInterval(600));let credential=try WatchCredentialRecord(scope:s,origin:URL(string:"https://example.com:443")!,cookie:cookie,approvedHeaders:[try HeaderCredentialRecord(name:"X-Hermes-Proxy",value:"secret2")],expiresAt:n.addingTimeInterval(600));let envelope=try WatchCredentialTransferEnvelope(envelopeID:UUID(),scope:s,issuedAt:n,expiresAt:n.addingTimeInterval(300),credential:credential);let data=try JSONEncoder().encode(envelope);#expect(try JSONDecoder().decode(WatchCredentialTransferEnvelope.self,from:data)==envelope);#expect(throws:(any Error).self){try WatchCredentialRecord(scope:s,origin:URL(string:"http://example.com")!,cookie:cookie,approvedHeaders:[],expiresAt:nil)}}
 @Test func rejectsScopeCookieHeaderPortDateAndSizeViolations()throws{#expect(throws:(any Error).self){try HeaderCredentialRecord(name:"Cookie",value:"x")};#expect(throws:(any Error).self){try HTTPCookiePropertyRecord(name:"n",value:"v",domain:"example.com",path:"relative",secure:true,expiresAt:nil)};let s=try scope();#expect(throws:(any Error).self){try WatchCredentialRecord(scope:s,origin:URL(string:"https://example.com:70000")!,cookie:try HTTPCookiePropertyRecord(name:"n",value:"v",domain:"example.com",path:"/",secure:true,expiresAt:nil),approvedHeaders:[],expiresAt:nil)}}
 @Test func credentialTypesAreStructurallyExcludedFromOrdinaryContracts()throws{let files=["Route.swift","DTOs.swift","Commands.swift","Operations.swift","TransportEnvelope.swift","OperationResults.swift","Receipts.swift","Diagnostics.swift"];let root=URL(fileURLWithPath:#filePath).deletingLastPathComponent().deletingLastPathComponent().deletingLastPathComponent().appendingPathComponent("Sources/WatchShared");for file in files{let text=try String(contentsOf:root.appendingPathComponent(file),encoding:.utf8);#expect(!text.contains("WatchCredentialRecord"));#expect(!text.contains("WatchCredentialTransferEnvelope"))}}
}
